//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Education</summary>
	[PublishedContentModel("education")]
	public partial class Education : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "education";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Education(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Education, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// City
		///</summary>
		[ImplementPropertyType("city")]
		public string City
		{
			get { return this.GetPropertyValue<string>("city"); }
		}

		///<summary>
		/// Degree/Course
		///</summary>
		[ImplementPropertyType("degreeCourse")]
		public string DegreeCourse
		{
			get { return this.GetPropertyValue<string>("degreeCourse"); }
		}

		///<summary>
		/// Description
		///</summary>
		[ImplementPropertyType("description")]
		public string Description
		{
			get { return this.GetPropertyValue<string>("description"); }
		}

		///<summary>
		/// End Year
		///</summary>
		[ImplementPropertyType("endYear")]
		public int EndYear
		{
			get { return this.GetPropertyValue<int>("endYear"); }
		}

		///<summary>
		/// Font Awesome Icon: Locate icons at: https://fontawesome.com/icons?d=gallery&s=brands,solid&m=free
		///</summary>
		[ImplementPropertyType("fontAwesomeIcon")]
		public string FontAwesomeIcon
		{
			get { return this.GetPropertyValue<string>("fontAwesomeIcon"); }
		}

		///<summary>
		/// School/Learning Platform
		///</summary>
		[ImplementPropertyType("schoolLearningPlatform")]
		public string SchoolLearningPlatform
		{
			get { return this.GetPropertyValue<string>("schoolLearningPlatform"); }
		}

		///<summary>
		/// Start Year
		///</summary>
		[ImplementPropertyType("startYear")]
		public int StartYear
		{
			get { return this.GetPropertyValue<int>("startYear"); }
		}

		///<summary>
		/// State
		///</summary>
		[ImplementPropertyType("state")]
		public string State
		{
			get { return this.GetPropertyValue<string>("state"); }
		}
	}
}
