//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Project</summary>
	[PublishedContentModel("project")]
	public partial class Project : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "project";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Project(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Project, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Carousel Shots: Provide a list of all images that will be displayed in the carousel.  Uses crop 700x435
		///</summary>
		[ImplementPropertyType("carouselShots")]
		public IEnumerable<IPublishedContent> CarouselShots
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("carouselShots"); }
		}

		///<summary>
		/// Description
		///</summary>
		[ImplementPropertyType("description")]
		public string Description
		{
			get { return this.GetPropertyValue<string>("description"); }
		}

		///<summary>
		/// Screenshot: Uses crop 700x475
		///</summary>
		[ImplementPropertyType("screenshot")]
		public IPublishedContent Screenshot
		{
			get { return this.GetPropertyValue<IPublishedContent>("screenshot"); }
		}

		///<summary>
		/// Site Url
		///</summary>
		[ImplementPropertyType("siteUrl")]
		public string SiteUrl
		{
			get { return this.GetPropertyValue<string>("siteUrl"); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("title")]
		public string Title
		{
			get { return this.GetPropertyValue<string>("title"); }
		}
	}
}
