//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Proposal Estimator</summary>
	[PublishedContentModel("proposalEstimator")]
	public partial class ProposalEstimator : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "proposalEstimator";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ProposalEstimator(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ProposalEstimator, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Domain Name: Radio List
		///</summary>
		[ImplementPropertyType("domainName")]
		public Newtonsoft.Json.Linq.JToken DomainName
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("domainName"); }
		}

		///<summary>
		/// Existing Website: Radio List
		///</summary>
		[ImplementPropertyType("existingWebsite")]
		public Newtonsoft.Json.Linq.JToken ExistingWebsite
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("existingWebsite"); }
		}

		///<summary>
		/// Existing Website Options: Radio List
		///</summary>
		[ImplementPropertyType("existingWebsiteOptions")]
		public Newtonsoft.Json.Linq.JToken ExistingWebsiteOptions
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("existingWebsiteOptions"); }
		}

		///<summary>
		/// Existing Wireframe: Radio List
		///</summary>
		[ImplementPropertyType("existingWireframe")]
		public Newtonsoft.Json.Linq.JToken ExistingWireframe
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("existingWireframe"); }
		}

		///<summary>
		/// Hourly Rate: Normal hourly rate
		///</summary>
		[ImplementPropertyType("hourlyRate")]
		public int HourlyRate
		{
			get { return this.GetPropertyValue<int>("hourlyRate"); }
		}

		///<summary>
		/// Migrating Content: Radio List
		///</summary>
		[ImplementPropertyType("migratingContent")]
		public Newtonsoft.Json.Linq.JToken MigratingContent
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("migratingContent"); }
		}

		///<summary>
		/// Mobile: Radio List
		///</summary>
		[ImplementPropertyType("mobile")]
		public Newtonsoft.Json.Linq.JToken Mobile
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("mobile"); }
		}

		///<summary>
		/// New Website: Radio List
		///</summary>
		[ImplementPropertyType("newWebsite")]
		public Newtonsoft.Json.Linq.JToken NewWebsite
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("newWebsite"); }
		}

		///<summary>
		/// Provide Images: Radio List
		///</summary>
		[ImplementPropertyType("provideImages")]
		public Newtonsoft.Json.Linq.JToken ProvideImages
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("provideImages"); }
		}

		///<summary>
		/// Purchase Images: Radio List
		///</summary>
		[ImplementPropertyType("purchaseImages")]
		public Newtonsoft.Json.Linq.JToken PurchaseImages
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("purchaseImages"); }
		}

		///<summary>
		/// Social Medias: Checkbox list
		///</summary>
		[ImplementPropertyType("socialMedias")]
		public Newtonsoft.Json.Linq.JToken SocialMedias
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("socialMedias"); }
		}

		///<summary>
		/// SSL: Radio List
		///</summary>
		[ImplementPropertyType("sSL")]
		public Newtonsoft.Json.Linq.JToken SSL
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("sSL"); }
		}

		///<summary>
		/// Taxonomy: Radio List
		///</summary>
		[ImplementPropertyType("taxonomy")]
		public Newtonsoft.Json.Linq.JToken Taxonomy
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("taxonomy"); }
		}

		///<summary>
		/// Web Hosting: Radio List
		///</summary>
		[ImplementPropertyType("webHosting")]
		public Newtonsoft.Json.Linq.JToken WebHosting
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("webHosting"); }
		}

		///<summary>
		/// Website Components: Checkbox list
		///</summary>
		[ImplementPropertyType("websiteComponents")]
		public Newtonsoft.Json.Linq.JToken WebsiteComponents
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("websiteComponents"); }
		}

		///<summary>
		/// Website Type: Radio List
		///</summary>
		[ImplementPropertyType("websiteType")]
		public Newtonsoft.Json.Linq.JToken WebsiteType
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("websiteType"); }
		}
	}
}
