//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Resume</summary>
	[PublishedContentModel("resume")]
	public partial class Resume : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "resume";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Resume(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Resume, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// About Background Image: Crop 804x1080
		///</summary>
		[ImplementPropertyType("aboutBackgroundImage")]
		public IPublishedContent AboutBackgroundImage
		{
			get { return this.GetPropertyValue<IPublishedContent>("aboutBackgroundImage"); }
		}

		///<summary>
		/// About Myself
		///</summary>
		[ImplementPropertyType("aboutMyself")]
		public IPublishedContent AboutMyself
		{
			get { return this.GetPropertyValue<IPublishedContent>("aboutMyself"); }
		}

		///<summary>
		/// Address
		///</summary>
		[ImplementPropertyType("address")]
		public Newtonsoft.Json.Linq.JToken Address
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("address"); }
		}

		///<summary>
		/// Application Patterns
		///</summary>
		[ImplementPropertyType("applicationPatterns")]
		public IEnumerable<string> ApplicationPatterns
		{
			get { return this.GetPropertyValue<IEnumerable<string>>("applicationPatterns"); }
		}

		///<summary>
		/// Career Title
		///</summary>
		[ImplementPropertyType("careerTitle")]
		public string CareerTitle
		{
			get { return this.GetPropertyValue<string>("careerTitle"); }
		}

		///<summary>
		/// Contact Conclusion: Inserted at the end of the Contact Me tab
		///</summary>
		[ImplementPropertyType("contactConclusion")]
		public IHtmlString ContactConclusion
		{
			get { return this.GetPropertyValue<IHtmlString>("contactConclusion"); }
		}

		///<summary>
		/// Contact Summary: Inserted at the top of the Contact Me tab
		///</summary>
		[ImplementPropertyType("contactSummary")]
		public IHtmlString ContactSummary
		{
			get { return this.GetPropertyValue<IHtmlString>("contactSummary"); }
		}

		///<summary>
		/// Email
		///</summary>
		[ImplementPropertyType("email")]
		public string Email
		{
			get { return this.GetPropertyValue<string>("email"); }
		}

		///<summary>
		/// Facebook
		///</summary>
		[ImplementPropertyType("facebook")]
		public string Facebook
		{
			get { return this.GetPropertyValue<string>("facebook"); }
		}

		///<summary>
		/// First Name
		///</summary>
		[ImplementPropertyType("firstName")]
		public string FirstName
		{
			get { return this.GetPropertyValue<string>("firstName"); }
		}

		///<summary>
		/// Form Picker
		///</summary>
		[ImplementPropertyType("formPicker")]
		public formulate.app.Types.ConfiguredFormInfo FormPicker
		{
			get { return this.GetPropertyValue<formulate.app.Types.ConfiguredFormInfo>("formPicker"); }
		}

		///<summary>
		/// Hobbies
		///</summary>
		[ImplementPropertyType("hobbies")]
		public string Hobbies
		{
			get { return this.GetPropertyValue<string>("hobbies"); }
		}

		///<summary>
		/// Instagram
		///</summary>
		[ImplementPropertyType("instagram")]
		public string Instagram
		{
			get { return this.GetPropertyValue<string>("instagram"); }
		}

		///<summary>
		/// Introduction Image: Crop 804x990
		///</summary>
		[ImplementPropertyType("introductionImage")]
		public IPublishedContent IntroductionImage
		{
			get { return this.GetPropertyValue<IPublishedContent>("introductionImage"); }
		}

		///<summary>
		/// Language Skills
		///</summary>
		[ImplementPropertyType("languageSkills")]
		public Newtonsoft.Json.Linq.JToken LanguageSkills
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("languageSkills"); }
		}

		///<summary>
		/// Last Name
		///</summary>
		[ImplementPropertyType("lastName")]
		public string LastName
		{
			get { return this.GetPropertyValue<string>("lastName"); }
		}

		///<summary>
		/// Library Knowledge: List of all libraries and languages that I use most often.
		///</summary>
		[ImplementPropertyType("libraryKnowledge")]
		public Newtonsoft.Json.Linq.JToken LibraryKnowledge
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("libraryKnowledge"); }
		}

		///<summary>
		/// Linked In
		///</summary>
		[ImplementPropertyType("linkedIn")]
		public string LinkedIn
		{
			get { return this.GetPropertyValue<string>("linkedIn"); }
		}

		///<summary>
		/// My Attributes: Added under my signature as a rotating list describing myself.
		///</summary>
		[ImplementPropertyType("myAttributes")]
		public IEnumerable<string> MyAttributes
		{
			get { return this.GetPropertyValue<IEnumerable<string>>("myAttributes"); }
		}

		///<summary>
		/// Phone Number
		///</summary>
		[ImplementPropertyType("phoneNumber")]
		public string PhoneNumber
		{
			get { return this.GetPropertyValue<string>("phoneNumber"); }
		}

		///<summary>
		/// SEO Checker
		///</summary>
		[ImplementPropertyType("sEOChecker")]
		public SEOChecker.MVC.MetaData SEochecker
		{
			get { return this.GetPropertyValue<SEOChecker.MVC.MetaData>("sEOChecker"); }
		}

		///<summary>
		/// SEO Redirects
		///</summary>
		[ImplementPropertyType("sEORedirects")]
		public object SEoredirects
		{
			get { return this.GetPropertyValue("sEORedirects"); }
		}

		///<summary>
		/// SEO Robots
		///</summary>
		[ImplementPropertyType("sEORobots")]
		public object SEorobots
		{
			get { return this.GetPropertyValue("sEORobots"); }
		}

		///<summary>
		/// SEO Sitemap
		///</summary>
		[ImplementPropertyType("sEOSitemap")]
		public object SEositemap
		{
			get { return this.GetPropertyValue("sEOSitemap"); }
		}

		///<summary>
		/// SEO Social
		///</summary>
		[ImplementPropertyType("sEOSocial")]
		public object SEosocial
		{
			get { return this.GetPropertyValue("sEOSocial"); }
		}

		///<summary>
		/// Signature: Crop 200x107
		///</summary>
		[ImplementPropertyType("signature")]
		public IPublishedContent Signature
		{
			get { return this.GetPropertyValue<IPublishedContent>("signature"); }
		}

		///<summary>
		/// Site Logo: Crop 140x140
		///</summary>
		[ImplementPropertyType("siteLogo")]
		public IPublishedContent SiteLogo
		{
			get { return this.GetPropertyValue<IPublishedContent>("siteLogo"); }
		}

		///<summary>
		/// Skill Details: Inserted at the top of the skills tab
		///</summary>
		[ImplementPropertyType("skillDetails")]
		public IHtmlString SkillDetails
		{
			get { return this.GetPropertyValue<IHtmlString>("skillDetails"); }
		}

		///<summary>
		/// Thank You Background Image: No crop
		///</summary>
		[ImplementPropertyType("thankYouBackgroundImage")]
		public IPublishedContent ThankYouBackgroundImage
		{
			get { return this.GetPropertyValue<IPublishedContent>("thankYouBackgroundImage"); }
		}

		///<summary>
		/// Thank you message
		///</summary>
		[ImplementPropertyType("thankYouMessage")]
		public IHtmlString ThankYouMessage
		{
			get { return this.GetPropertyValue<IHtmlString>("thankYouMessage"); }
		}

		///<summary>
		/// Tools of the Trade
		///</summary>
		[ImplementPropertyType("toolsOfTheTrade")]
		public Newtonsoft.Json.Linq.JToken ToolsOfTheTrade
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("toolsOfTheTrade"); }
		}

		///<summary>
		/// Twitter
		///</summary>
		[ImplementPropertyType("twitter")]
		public string Twitter
		{
			get { return this.GetPropertyValue<string>("twitter"); }
		}
	}
}
